#===========短信配置========================================================================================#
sms:
  key: 6113fd29f08399232775285a216486
  companyId: 162
  username: aiiduo
  password: aishio123456
  url: http://47.93.158.165:88/v2sms.aspx
  content: 【爱士多】您的验证码是{0}。如非本人操作，请忽略本短信
  #===========极光推送========================================================================================#
jpush:
  appkey: b38873f153807506fb4381
  secret: 55900cdef24a532cbb9700
  apns: false

