spring:
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

  #mq配置
    rabbitmq:
      host: 10.10.20.168
      port: 5672
      username: admin
      password: 123456
      publisher-confirms: true
      virtual-host: /
      listener:
          simple:
            auto-startup: false

#mysql配置
druid:
  username: root
  #root
  password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
  url: jdbc:mysql://10.10.20.168:3306/istore?cuseUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
  #123456
  #password: Biyu5YzU+6sxDRbmWEa3B2uUcImzDo0BuXjTlL505+/pTb+/0Oqd3ou1R6J8+9Fy3CYrM18nBDqf6wAaPgUGOg==
  #url: jdbc:mysql://192.168.0.103:3306/tianmao?cuseUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
  max-wait: 60000
  time-between-eviction-runs-millis: 60000
  min-evictable-idle-time-millis: 300000
  validation-query: SELECT 1 FROM DUAL
  test-While-Idle: true
  test-on-return: false
  pool-prepared-statements: false
  max-pool-prepared-statement-per-connection-size: 20
  filters: stat,wall,log4j,config
  connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true
  monitor:
    enabled: false
    druid-stat-view: /druid/*
    druid-web-stat-filter: /*
    allow: 219.230.50.107,127.0.0.1
    deny: 192.168.1.73
    login-username: admin
    login-password: 123456
    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    reset-enable: false

#quartz集群配置
quartz:
  #线程调度器id
  instanceId: istore
  # 线程调度器实例名,集群节点中必须相同
  instanceName: quartzScheduler
  #不更新检测新版本
  skipUpdateCheck: true
   # 线程池的线程数，即最多10个任务同时跑
  threadCount: 10
  #等待多久quartz开始执行（秒）
  startupDelay: 10
  # 如何存储任务和触发器等信息
  jobStoreClass: org.quartz.impl.jdbcjobstore.JobStoreTX
  # 驱动代理
  driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  # 表前缀
  tablePrefix: qrtz_
  # 数据源
  dataSource: mysql
  # 是否集群
  isClustered: true

