#===========短信配置========================================================================================#
sms:
  key: 552211
  companyId: 111
  username: 11
  password: 222
  url: http://47.93.158.165:88/v2sms.aspx
  content: 【】您的验证码是{0}。如非本人操作，请忽略本短信
  #===========极光推送========================================================================================#
jpush:
  appkey: 666
  secret: 111
  apns: false
#===========邮件配置===========================================================================================#
spring:
  mail:
    name: 爱士多
    subject: 爱士多验证码
    host: smtp.163.com
    port: 465
    username: qq171375063@163.com
    password: shewoqishui520
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

